//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.RecievedMails = new HashSet<RecievedMail>();
            this.MailingListLines = new HashSet<MailingListLine>();
        }
    
        ///<summary>The first name of the email address's owner.</summary>
        public string FirstName { get; set; }
        ///<summary>The last name of the email address's owner.</summary>
        public string LastName { get; set; }
        ///<summary>The email address of this Address entity.</summary>
        public string Email { get; set; }
        public long AddressID { get; set; }
    
        ///<summary>A Collection of RecievedMail entities which represent years in which this address sent the user an email.</summary>
        public virtual ICollection<RecievedMail> RecievedMails { get; set; }
        ///<summary>A Collection of all MailingListLine entities to which this Address belongs.</summary>
        public virtual ICollection<MailingListLine> MailingListLines { get; set; }
    }
}
