//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.ReceivedMails = new HashSet<ReceivedMail>();
            this.MailingListLines = new HashSet<MailingListLine>();
        }
    
        ///<summary>The first name of the person represented by this Address.</summary>
        public string FirstName { get; set; }
        ///<summary>The last name of the person represented by this Address.</summary>
        public string LastName { get; set; }
        ///<summary>The email address of the person represented by this Address.</summary>
        public string Email { get; set; }
        public long AddressID { get; set; }
    
        ///<summary>A collection  of RecievedMail entities representing years that this Address sent the user an email.</summary>
        public virtual ICollection<ReceivedMail> ReceivedMails { get; set; }
        ///<summary>A collection of MailingListLine entities that represent the MailingLists that this Address belongs to.</summary>
        public virtual ICollection<MailingListLine> MailingListLines { get; set; }
    }
}
