//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.RecievedMails = new HashSet<RecievedMail>();
            this.MailingListLines = new HashSet<MailingListLine>();
        }
    
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public long addressID { get; set; }
    
        public virtual ICollection<RecievedMail> RecievedMails { get; set; }
        public virtual ICollection<MailingListLine> MailingListLines { get; set; }
    }
}
