//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingListLine
    {
        public long listID { get; set; }
        public long addressID { get; set; }
    
        public virtual MailingList MailingList { get; set; }
        public virtual Address Address { get; set; }
    }
}
