//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingList
    {
        public MailingList()
        {
            this.MailingListLines = new HashSet<MailingListLine>();
        }
    
        public long listID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<MailingListLine> MailingListLines { get; set; }
    }
}
