//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingList
    {
        public MailingList()
        {
            this.MailingListLines = new HashSet<MailingListLine>();
        }
    
        public long ListID { get; set; }
        ///<summary>The name of this MailingList.</summary>
        public string Name { get; set; }
    
        ///<summary>A collection of MailingListLines representing the Address entities that are included in this MailingList.</summary>
        public virtual ICollection<MailingListLine> MailingListLines { get; set; }
    }
}
