//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer
{
    using System;
    using System.Collections.Generic;
    
    ///<summary>Represents an email message template that the user may send to one or more Address.</summary>
    public partial class Message
    {
        ///<summary>The body of the email message.</summary>
        public string Body { get; set; }
        ///<summary>The subject of the email message.</summary>
        public string Subject { get; set; }
        public long MailID { get; set; }
    }
}
