//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mailer
{
    using System;
    using System.Collections.Generic;
    
    ///<summary>Represents a year that a user sent an email to the user.</summary>
    public partial class ReceivedMail
    {
        public long AddressID { get; set; }
        ///<summary>The year in which the corresponding Address of this RecievedMail sent the user an email.</summary>
        public long Year { get; set; }
    
        ///<summary>The Address of the person who sent an email to the user in this year.</summary>
        public virtual Address Address { get; set; }
    }
}
